services:
  redis_db:
    container_name: redis_db
    image: redislabs/redismod
    ports:
      - 6379:6379
  app:
    container_name: app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis_db

    entrypoint: "flask --app src.app run --host 0.0.0.0"

